### ISSUE TITLE
Feature Request: Support for Loading Models Spanning Multiple Files

### ISSUE THREAD

**Issue by NikolayIT** [SciSharp/LLamaSharp#128]
Currently, the model loading utility only supports models that are saved in a single file. However, there are large models that are saved across multiple binary files. We need to add support for loading such segmented models.

For example `WizardCoder-Python-34B-V1.0` (https://huggingface.co/WizardLM/WizardCoder-Python-34B-V1.0) consists of 7 files as follows:
* pytorch_model-00001-of-00007.bin
* pytorch_model-00002-of-00007.bin
* pytorch_model-00003-of-00007.bin
* pytorch_model-00004-of-00007.bin
* pytorch_model-00005-of-00007.bin
* pytorch_model-00006-of-00007.bin
* pytorch_model-00007-of-00007.bin

**Comment by AsakusaRinne** [comment]
Hi, could you please check that if the newest llama.cpp support loading pytorch weights directly? I remember that llama.cpp only supports loading ggml weights. For pytorch weights you need to convert them to ggml weights first and then load it. Since LLamaSharp is a binding of llama.cpp, we'll follow it if it has this feature.
