### ISSUE TITLE
Pinvoke Issue when using .net Framework 4.8

### ISSUE THREAD

**Issue by Phreak87** [SciSharp/LLamaSharp#14]
i try to implement the latest version of LLamaSharp in my project which is based on .net Framework 4.8 (X64).
as far i know .net 4.8 is fully compatible with .Net Standard 2.0 (LLamaSharp is available for .net 2.0 this in Nuget).
i can access methods from LLamaSharp. But if i try to load the model i get a "Pinvoke Incompatible" Error Message. 
not sure if this is a issue with LLamaSharp or .Net. Hopefully you can help or give a hint how to fix.

**Comment by AsakusaRinne** [comment]
Hi, thank you for reporting us this error. I'll try to fix it 1-2 days later. I'm a bit busy now and I'm sorry for the delay. :)

**Comment by Xsanf** [comment]
I included this library in Unity 2021.3.22f1
Since Unity hasn't had time to migrate to later versions of NET, a few changes had to be made.

LLamaParams.cs replacing struct with class because memory allocation has changed.
public struct LLamaParams > public class LLamaParams
===================
LLamaTypes.cs - Added

using System.ComponentModel;
namespace System.Runtime.CompilerServices
{
     [EditorBrowsable(EditorBrowsableState.Never)]
     internal static class IsExternalInit { }
}
Because earlier versions don't have this definition.
I did not set the compilation conditions, because I did it in haste.

So that the model can be run under Unity natively.

**Comment by latenightbuddha** [comment]
It appears that this has not been addressed yet, I am using .net Framework 4.8 (_used nuget for the two packages, LLamaSharp ver0.4.0 and LLamaSharp.Backend.Cpu ver0.3.1_) outputted as an x64 binary but this code below ->
`LLamaModel llamaModel = new LLamaModel(modelParams); ` results in an error at runtime:
**System.Runtime.InteropServices.MarshalDirectiveException: 'Method's type signature is not PInvoke compatible.'**

**Comment by martindevans** [comment]
Is everything working on .NET Framework now?
