### ISSUE TITLE
The chat API could be only used under interactive model

### ISSUE THREAD

**Issue by ugurkaancalim** [SciSharp/LLamaSharp#19]
Hi,

I have upgraded LLamaSharp version from 0.2.2 to 0.3.0. I'm getting this error below now:

**The chat API could be only used under interactive model**

StackTrace:

   at LLama.LLamaModel.Chat(String text, String prompt, String encoding)
   at LLama.ChatSession`1.<Chat>d__5.MoveNext()
   at Program.<Main>$(String[] args) in D:\Program.cs:line 15

![resim_2023-06-09_170401032](https://github.com/SciSharp/LLamaSharp/assets/12467865/fc5a1230-ccd6-43a8-884e-07446bb86037)

When I turn LLamaSharp version to 0.2.2, it works fine.

Anyone can help me?

**Comment by AsakusaRinne** [comment]
Please add `interactive: true` when initializing the `LLamaParams`. Yes in v0.2.2 it could work but it may have some strange behaviors because in fact non-interact mode is not expected in chat session. I have to confess that the design in v0.3.0 is not reasonable because it should not require users to set `interact=true` manually when using chat session. It will be optimized in the next release.

**Comment by yazilimciabi1** [comment]
Thank you for the answer. It worked.

**Comment by faceslog** [comment]
> Please add `interactive: true` when initializing the `LLamaParams`. Yes in v0.2.2 it could work but it may have some strange behaviors because in fact non-interact mode is not expected in chat session. I have to confess that the design in v0.3.0 is not reasonable because it should not require users to set `interact=true` manually when using chat session. It will be optimized in the next release.

Thanks as for now could be awesome to add the interactive: true in the example provided in the README. Thanks tho.
