### ISSUE TITLE
"LLAMA_ASSERT: ...\development\llama\llama.cpp\llama.cpp:904: false" ERROR

### ISSUE THREAD

**Issue by yazilimciabi1** [SciSharp/LLamaSharp#21]
Hi there,

I got this error when i tried to use [OpenLM's 3B ](https://huggingface.co/SlyEcho/open_llama_3b_ggml/tree/main) model open-llama-3b-q4_1.bin 

**LLAMA_ASSERT: ...\development\llama\llama.cpp\llama.cpp:904: false**

![resim_2023-06-09_173049611](https://github.com/SciSharp/LLamaSharp/assets/12467865/119d99a3-9428-4549-9465-719d768fef60)

It works fine with 7B model (open-llama-7b-q4_0) of OpenLM.

Thanks for your help.

**Comment by AsakusaRinne** [comment]
The model you use was published 2 days ago. I guess it was converted and quantized by the latest master branch of llama.cpp, making it incompatible with the current backend of `LLamaSharp`. We'll follow up `llama.cpp` to update `LLamaSharp.Backend` to the latest llama.cpp version next week. Forgive us about the delay because we're refactoring the project now to provide more C#-style APIs and improve the performance.

**Comment by AsakusaRinne** [comment]
Hi, the master branch has been updated. Would you like to have a try with it? I'd like to try it myself first but I found that I couldn't download the model in the link... I'm not sure if it's only my problem.

**Comment by yazilimciabi1** [comment]
I updated to LlamaSharp to 0.4.0 but I still get error. 

I think the problem is about model..

**Comment by AsakusaRinne** [comment]
Please have a try with v0.4.1-preview, or the master branch. Note that currently v0.4.1 only supports cpu backend. I've tried it in my local environment and it worked.

What I did is downloading the fp16 weight and quantize it with v0.4.1-preview and then run the quantized model. Not sure if directly running the quantized models in huggingface would work.
