### ISSUE TITLE
LoadSession doesn't work

### ISSUE THREAD

**Issue by Hendrik-Jacobs** [SciSharp/LLamaSharp#236]
Hi,
I'm trying to save/load a session. Saving works fine, a directory and two files are getting created. 
But when I try to load from the same path nothing happens. Session.History.Messages doesn't contain any message after loading and I don't get an exception.

Thank you for your help!

**Comment by AsakusaRinne** [comment]
Hi, the state save/load of `ChatSession` does not contain chat history now. This is because when designing it, we thought users may take state and history as independent ones. If you want to save/load history, a quick fix is to inherit `ChatSession` and override `SaveSession` and `LoadSession`.

@martindevans Do you think we should reconsider saving and loading session with chat history?

**Comment by Hendrik-Jacobs** [comment]
Ok, thank you for your response!

**Comment by AsakusaRinne** [comment]
Closed this issue as completed now. If you have any other inconvenience when saving the session, please feel free to tell us. :)

**Comment by martindevans** [comment]
> Do you think we should reconsider saving and loading session with chat history?

Honestly not really sure. I haven't done much work at the higher level of the executors, most of what I've done has been adding new lower level features.

With things like llama_decode and batch decoding we're probably going to need to design a whole new systems for executors based on that, but I haven't fully throught through how to do that yet.
