### ISSUE TITLE
0.8.0 - GGML_ASSERT src0->backend != GGML_BACKEND_GPU_SPLIT

### ISSUE THREAD

**Issue by AlShadi** [SciSharp/LLamaSharp#280]
Running the Cuda12 backend with llama-2-7b-chat.f16.gguf
I was trying to test the performance of the new 0.8.0 with **10/35** layers on the GPU. Previous results with 0.5.1 and 0.7.0 were:
0.5.1 - Duration: 00:00:39.6480427
0.7.0 - Duration: 00:00:53.3219226

Unfortunately, 0.8.0 gives the error:
GGML_ASSERT: D:\a\LLamaSharp\LLamaSharp\ggml-cuda.cu:7265: src0->backend != GGML_BACKEND_GPU_SPLIT
Error occurs with **35/35** layers on GPU, too. No errors with **0/35** layers on GPU.
0.8.0 - 0/35 layers - Duration: 00:00:59.4659602

No Issues with a 70b model, though.
Cuda12 Backend - 35 layers - llama-2-70b-chat.Q5_K_M.gguf
0.5.1 - Duration: 00:02:13.3029884
0.7.0 - Duration: 00:06:00.6600464
0.8.0 - Duration: 00:02:16.5664266 - performance issue is fixed!

**Comment by AsakusaRinne** [comment]
Hi, glad the hear that the performance regression has gone away. Since the error is thrown by native library, could you please run with `llama.cpp` with exactly the same configurations to see if it's an issue of llama.cpp or LLamaSharp? Please use [207b519](https://github.com/ggerganov/llama.cpp/commit/207b51900e15cc7f89763a3bb1c565fe11cbb45d) of llama.cpp

**Comment by AlShadi** [comment]
The issue has gone away with 0.8.1
