### ISSUE TITLE
'tensor splits length must equal 16'

### ISSUE THREAD

**Issue by JohnGalt1717** [SciSharp/LLamaSharp#308]
I'm setting TensorSplits  = new LLama.Abstractions.TensorSplitsCollection([12F, 4F]);

Yet I get the above error despite them equaling 16.

I'm trying to distribute memory and load across 2 Cuda GPUs which is supposed to be supported by Llama.cpp now so that I can load a model with a large context length into GPU.

**Comment by martindevans** [comment]
What is the _exact_ text of the error you're getting?

**Comment by JohnGalt1717** [comment]
Sorry, fixed the title which was supposed to be the exact error until auto-correct got involved.

**Comment by martindevans** [comment]
Aha, yes I thought that might be the problem. The error is telling you that the **length** of the array must be 16 (because that's the maximum number of devices supported by llama.cpp).

So you'd want to do something like this:

```csharp
TensorSplits = new LLama.Abstractions.TensorSplitsCollection([12F, 4F, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]);
```

I've just opened a PR (#310) which would make your initial code work :)

**Comment by JohnGalt1717** [comment]
Awesome! Thanks!
