### ISSUE TITLE
Multiple sessions on one model.

### ISSUE THREAD

**Issue by BruceKristelijn** [SciSharp/LLamaSharp#41]
Hi there, would love to have multiple sessions on the same model but th sessions seem to remember new information given by the other chat sessions. In the docs and settings I couldn't find anyhting. I am curious if this is somemthing I am doing wrong?

**Comment by martindevans** [comment]
At the moment the model weights and the context are all bound together in one object. You need to save and restore "states" to have two contexts in one set of weights. This is due to how llama.cpp itself used to work.

They've since made a change which splits model weights and model contexts into two separate things, so you can make multiple contexts from one set of shared weights. My PR (#64) partially addresses this by adding in support for the new loading system. Future PRs will modify the higher level APIs to use this.

**Comment by BruceKristelijn** [comment]
Thanks for the response. I am trying it right now but my responses seems to lose some context. I assumed that when a state is loaded / saved it retains the chat and prompt history, or am I mistaken?

**Comment by BruceKristelijn** [comment]
I tried including the chat history after loading the session again aswell but this seemed to reset the "memory" of the previous conversation aswell,

**Comment by martindevans** [comment]
Is this testing all being done on top of my PR (#64), with `master` or with some other version?

**Comment by BruceKristelijn** [comment]
> 

Not yet, this was my next course of action. Was hoping I understoot the behaviour correctly first.

**Comment by martindevans** [comment]
I'm not too sure, sorry. I've been contributing PRs on some of the lower level bits of the stack but not the "higher level "stuff yet. I do know there are a few layers, which should all save and reload state together (executor, context etc), so maybe try backtracing some of that to check it all looks reasonable.

**Comment by BruceKristelijn** [comment]
Thanks, I just build your PR and it seems to work better without changing a lot of code which is great! Might be the wrong place to ask buiit I couldn't find it in sourcecode. Do you know if LLamaSharp adds things like 'Assistant:', and 'User:' to the chat?

**Comment by martindevans** [comment]
[0.4.2](https://github.com/SciSharp/LLamaSharp/releases/tag/v0.4.2-preview) is out now. Does that resolve this issue?
