### ISSUE TITLE
LLamaWeights.LoadFromFile

### ISSUE THREAD

**Issue by vvdb-architecture** [SciSharp/LLamaSharp#431]
I'm using LLamaSharp with Microsoft's [Kernel Memory](https://github.com/microsoft/kernel-memory).
Kernel Memory needs an implementation of a text generator and an embedding generator. 

Both implementations call `LLamaWeights.LoadFromFile`, which returns a `LLamaWeights` instance. Because `LLamaWeights.LoadFromFile` is called twice, so the weights are loaded twice.

My question is this: would it be safe to load `LLamaWeights.LoadFromFile` only once and pass it to both implementations?

If the answer is yes, is the resulting `LLamaWeights` thread-safe? I.e. can multiple threads concurrently call `_weights.CreateContext' on the same `_weights` instance?

To be clear: we're talking about multiple contexts on a single model here. I know that llama.cpp "might" be thread safe in these cases, but the comments over there are not clear to me.

**Comment by martindevans** [comment]
> I know that llama.cpp "might" be thread safe in these cases, but the comments over there are not clear to me.

Unfortunately that's the best answer available right now - LLamaSharp is as threadsafe as llama.cpp it, but it's unclear how threadsafe that actually is :(

> would it be safe to load `LLamaWeights.LoadFromFile` only once and pass it to both implementations?

I haven't worked on the Kernel Memory part of LLamaSharp, @Oceania2018 may have a better answer than I do. I **think** the reason the weights are not shared is because a model can either be loaded in embedding mode (in which case it can't be used for inference) or in inference mode (in which case it can't be used for embedding).

**Comment by martindevans** [comment]
I've closed this issue since there's been no more activity and the question was answered, but feel free to re-open it if you want to know more :)
