### ISSUE TITLE
FileNotFoundException on MacOS Arm64 

### ISSUE THREAD

**Issue by rubiktubik** [SciSharp/LLamaSharp#44]
Hi,

i want to use your awesome library on my macbook pro m1 arm64 mac.

I have created a new console .NET 7 application, added the needed nugets
![grafik](https://github.com/SciSharp/LLamaSharp/assets/115047/6ccccb31-13ff-4f39-98ea-46ed1bd09904)

Added some code:

```cs
using LLama.Common;
using LLama;

string modelPath = "<Your model path>" // change it to your own model path
var prompt = "Transcript of a dialog, where the User interacts with an Assistant named Bob. Bob is helpful, kind, honest, good at writing, and never fails to answer the User's requests immediately and with precision.\r\n\r\nUser: Hello, Bob.\r\nBob: Hello. How may I help you today?\r\nUser: Please tell me the largest city in Europe.\r\nBob: Sure. The largest city in Europe is Moscow, the capital of Russia.\r\nUser:";

// Initialize a chat session
var ex = new InteractiveExecutor(new LLamaModel(new ModelParams(modelPath, contextSize: 1024, seed: 1337, gpuLayerCount: 5)));
ChatSession session = new ChatSession(ex);

Console.WriteLine();
Console.Write("User: ");
while (prompt != "stop")
{
    foreach (var text in session.Chat(prompt, new InferenceParams() { Temperature = 0.1f, AntiPrompts = new List<string> { "User:" } }))
    {
        Console.Write(text);
    }
    prompt = Console.ReadLine();
}
```

But when i use `dotnet run` i get 

the following error:

```bash
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'LLamaSharp, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```
But in my binary folder everything is there:

![grafik](https://github.com/SciSharp/LLamaSharp/assets/115047/93647900-b1ff-4913-b50f-1a7480b28a94)

Do you have an idea what i'am doing wrong?

**Comment by SignalRT** [comment]
You need libllama.dylib in the binary directory.
If you clone the current LlamaSharp repo, you should be able to run the example in the MacOS because library is in the runtime directory.

If you clone my fork you should be able to run the example but using Metal, so the inference will be a lot faster. In that case the files that are being used a libllama.dylib and ggml-metal.metal that should be in the bin directory.

You are using nugget packages, and that it seems that you should be used the **preview** package:
https://www.nuget.org/packages/LLamaSharp.Backend.Cpu/0.4.1-preview

But if that is not copying the file libllama.dylib it will not work.

**Comment by rubiktubik** [comment]
Thank you for your hint on solving the problem. I doesn't work with the nuget package but i used your fork and added my custom project to the solution. 
With the nuget i would be nicer but perhaps it works if your PR is merged

**Comment by redthing1** [comment]
I have this issue too.
