### ISSUE TITLE
Whisper support

### ISSUE THREAD

**Issue by Lyrcaxis** [SciSharp/LLamaSharp#652]
Hi, is anyone interested in Speech-To-Text support? (whisper.cpp)

If someone is willing to create the native handles for it I'd be glad to contribute the mid-level & high-level bindings for it.

**Comment by AsakusaRinne** [comment]
Hi, speech-to-text is an interesting topic. However I don't think we would include the full binding of whisper.cpp in LLamaSharp because there is already a binding for it ([whisper.net](https://github.com/sandrohanea/whisper.net)). It will be great if you would like to add an example to LLamaSharp to show how to use it to implement the workflow of audio-text-response with whisper.net and LLamaSharp. :)

**Comment by Lyrcaxis** [comment]
Neat I wasn't aware of that library. I'll give it a try over the weekend and post back!

**Comment by AsakusaRinne** [comment]
I'm looking forward to that!

**Comment by Lyrcaxis** [comment]
I do have a satisfying example where speech is automatically being parsed and sent to the LLM to invoke responses, resulting in speech-text chat, but it requires adding the Whisper.NET & NAudio packages to the solution -- how should this be approached for the LlamaSharp example?

**Comment by AsakusaRinne** [comment]
Is `Whisper.NET` & `NAudio` cross-platform? To me it's okay to add the two packages to `LLama.Example` project of this repo as long as they are cross-platform (working on Windows/Linux/MAC)

**Comment by Lyrcaxis** [comment]
👌Yup, both are cross platform! I'll add them and make a PR later today, then!

**Comment by AsakusaRinne** [comment]
No rush for that. :) Thank you for your contribution!

**Comment by martindevans** [comment]
[Example for Whisper+Llama](https://github.com/SciSharp/LLamaSharp/blob/master/LLama.Examples/Examples/SpeechChat.cs) was merged a while ago (thanks for that @Lyrcaxis!) so I'll close this issue now.
