### ISSUE TITLE
LLamaSharp runtime binaries don't support Rosetta2

### ISSUE THREAD

**Issue by abhiaagarwal** [SciSharp/LLamaSharp#752]
### Description

Hi there,

I'm attempting to integrate LLamaSharp with a C#-based game that is stuck with Rosetta emulation on M1 Macs. Unfortunately, the regular builds are compiled with AVX (I believe?) which Rosetta can't emulate, causing a crash. I compiled with minimal support from the Llama.cpp repo and it works fine. 

I'm not sure if this is something that needs to be addressed by the library itself, but felt worth noting here.

**Comment by martindevans** [comment]
There should be non AVX binaries (it's the ones in [this folder](https://github.com/SciSharp/LLamaSharp/tree/master/LLama/runtimes/deps)).

Try running your application with this at the start:

```csharp
NativeLibraryConfig
   .All
   .WithLogCallback((level, message) =>
   {
       Console.WriteLine($"[llama {level}]: {message.TrimEnd('\n')}");
   });
```

It will log out what the binary selection process is doing, which should help diagnose why it's choosing AVX over noavx.

**Comment by abhiaagarwal** [comment]
Those are `.so` files, right? I don't think MacOS can load those. It's only looking for the dylibs based on https://github.com/SciSharp/LLamaSharp/blob/c51a65fcbd1bdc554ee1c41a2f2f343f7f9808c7/LLama/Native/Load/NativeLibraryUtils.cs#L23.

**Comment by martindevans** [comment]
Aha yes sorry I forgot about that. In that case yes you're right, as you can see [here](https://github.com/SciSharp/LLamaSharp/blob/master/.github/workflows/compile.yml#L280) the MacOS+x64 binaries are compiled with AVX support.

If you're interested in submitting a PR to fix this it should be fairly simple.
 - [Here](https://github.com/SciSharp/LLamaSharp/blob/master/.github/workflows/compile.yml#L29) is an example of adding a new step to the build matrix for noavx.
 - [Here](https://github.com/SciSharp/LLamaSharp/blob/master/.github/workflows/compile.yml#L364) the files are being copied into their final location, you'll need to add somewhere for the noavx binaries to go (probably add the noavx binaries into that folder, and create an avx folder for the existing ones).
 - Runtime loading will need modifying to load the relevant binary. That's probably in [here](https://github.com/SciSharp/LLamaSharp/blob/master/LLama/Native/Load/NativeLibraryWithMacOrFallback.cs). @AsakusaRinne might have a better idea then me since they worked on this recently.

**Comment by abhiaagarwal** [comment]
Yeah, I already hacked together a fix in my codebase – the only problem is that it's relatively convoluted to figure out "whether we're running under rosetta emulation without AVX support", because AVX works fine for regular Intel-based Macs (even though the hardware platform is increasingly rare).

**Comment by martindevans** [comment]
Does [this](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.avx.issupported?view=net-8.0#system-runtime-intrinsics-x86-avx-issupported) not work under Rosetta?

**Comment by AsakusaRinne** [comment]
> Runtime loading will need modifying to load the relevant binary. That's probably in [here](https://github.com/SciSharp/LLamaSharp/blob/master/LLama/Native/Load/NativeLibraryWithMacOrFallback.cs). @AsakusaRinne might have a better idea then me since they worked on this recently.

It's good to make changes at this place. It's better to split this class into `NativeLibraryFallback` and `NativeLibraryForMac` because Rosetta only appears with MAC. But don't worry, I can do it after your PR. :)

**Comment by abhiaagarwal** [comment]
> Does [this](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.avx.issupported?view=net-8.0#system-runtime-intrinsics-x86-avx-issupported) not work under Rosetta?

Yep, I didn't think about tackling it at this angle. I'll open a PR later today. Thank you :)
