### ISSUE TITLE
Semantic Kernel - Home Automation Sample

### ISSUE THREAD

**Issue by louislewis2** [SciSharp/LLamaSharp#764]
### Description

Good day,

I discovered an example on the Semantic Kernel repo.
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Demos/HomeAutomation/Program.cs

I have been trying to work out how using that example, one would implement it using LlamaSharp?
I think having an example like that, would help many people.

Is this even possible?
I am having issues, where the plugins are not being called, despite how I register them.

Thank you

**Comment by zsogitbe** [comment]
That example uses the OpenAI feature AutoInvokeKernelFunctions, which is not available in LLamaSharp. AutoInvokeKernelFunctions triggers a mechanism to call kernel plugins/functions "automatically". Where automatically means that the chat model indicates to call a function. For this you need a specialized model.

You can make all of this work without the OpenAI part "manually" as follows, you define the kernel functions and you ask the chat model to indicate the user's intention and then call the Kernel function. This is what is actually happening internally in the OpenAI implementation, so you can do the same.

But, this is all a bit outdated because there is a new way called Handlebars plan calling. You can ask a model to create a plan and then execute the plan which may contain a whole process with several plugins and functions.
All of this is state of the art today and relatively complex and you will need some time to understand it...

**Comment by SignalRT** [comment]
The example is now in the master. Thank you @zsogitbe
